version: "3.8"
services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: motorway
    ports:
      - 5432:5432
    volumes:
      - pgdata:/pgdata
    networks:
      - motorway
  dbTest:
    image: postgres
    container_name: dbTest
    hostname: localhost
    environment:
      POSTGRES_USER: testUser
      POSTGRES_PASSWORD: testPassword
      POSTGRES_DB: motorwayTest
    ports:
      - "5400:5432"
    networks:
      - motorway
  node_app:
      container_name: node_app
      hostname: node_app
      build: .
      depends_on:
        - db
        - dbTest
      restart: on-failure
      command: bash -c "npm run migrateUp && npm run start"
      environment:
        DB_HOST: db
        DB_USER: user
        DB_PASS: password
        DB_TEST_HOST: localhost
        TEST_USER: testUser
        TEST_PASS: testPassword
        NODE_ENV: development
        DEV: motorway
      volumes:
        - ./:/app
        - /app/node_modules
      ports:
        - 3000:3000
      networks:
        - motorway
volumes:
  pgdata:
networks:
  motorway: